/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdmissionForm;

/**
 *
 * @author fgbal
 */
public class balangaCampus extends javax.swing.JFrame {

    /**
     * Creates new form BalangaCampusCourse
     */
    public balangaCampus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bpsuHeader = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        balangaCourseTable = new javax.swing.JTable();
        returnbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bpsuHeader.setBackground(new java.awt.Color(255, 255, 255));
        bpsuHeader.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        bpsuHeader.setForeground(new java.awt.Color(85, 22, 29));
        bpsuHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpsuHeader.setText("BALANGA CAMPUS");
        bpsuHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 22, 29), 2));
        bpsuHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        balangaCourseTable.setBackground(new java.awt.Color(204, 204, 204));
        balangaCourseTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 22, 29), 2));
        balangaCourseTable.setForeground(new java.awt.Color(30, 30, 30));
        balangaCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bachelor of Secondary Education", "Social Studies", "All Strands/Tracks", "Grade 11 Final GWA 80"},
                {"Bachelor of Science in Accountancy", "", "ABM", "Grade 11 Final GWA 85"},
                {"Bachelor of Science in Business Administration", "Marketing Management", "ABM", "Grade 11 Final GWA 80"},
                {"Bachelor of Public Administration", null, "All Strands/Tracks", "Grade 11 Final GWA 80"},
                {"Bachelor of Culture and Arts Education", null, "All Strands/Tracks", "Grade 11 Final GWA 85"},
                {"Bachelor of Human Services  ", null, "All Strands/Tracks", "Grade 11 Final GWA 80"}
            },
            new String [] {
                "PROGRAM", "MAJOR", "STRAND", "MINIMUM GWA"
            }
        ));
        balangaCourseTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(balangaCourseTable);
        balangaCourseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        returnbutton.setBackground(new java.awt.Color(85, 22, 29));
        returnbutton.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        returnbutton.setText("RETURN");
        returnbutton.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpsuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bpsuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(returnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(balangaCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(balangaCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(balangaCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(balangaCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new balangaCampus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable balangaCourseTable;
    private javax.swing.JLabel bpsuHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton returnbutton;
    // End of variables declaration//GEN-END:variables
}
