/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdmissionForm;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author HANNAH
 */
public class collegeAdmissionSystem extends javax.swing.JFrame {
    
    private userData userData;

    public collegeAdmissionSystem(userData userData) {
        this.userData = userData;
        initComponents();
    }

    collegeAdmissionSystem() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        personalInfoBtn = new javax.swing.JButton();
        educBackgroundBtn = new javax.swing.JButton();
        gradesBtn = new javax.swing.JButton();
        courseBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInfoPanel = new javax.swing.JPanel();
        fullnameLabel = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        birthday = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        emailAddLabel = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        studCpNumLabel = new javax.swing.JLabel();
        addressTxtField = new javax.swing.JTextField();
        emailAddTxtField = new javax.swing.JTextField();
        studCpnumTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        givenNameTxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        middleNameTxtField = new javax.swing.JTextField();
        sexComboBox = new javax.swing.JComboBox<>();
        nextBtn1 = new javax.swing.JButton();
        returnbtn1 = new javax.swing.JButton();
        educBGPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        returnbtn2 = new javax.swing.JButton();
        nextBtn2 = new javax.swing.JButton();
        schoolComboBox = new javax.swing.JComboBox<>();
        addSchoolTxtField = new javax.swing.JTextField();
        gradespanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        englishLabel = new javax.swing.JLabel();
        mathLabel = new javax.swing.JLabel();
        scienceLabel = new javax.swing.JLabel();
        filipinoLabel = new javax.swing.JLabel();
        mathTxtField = new javax.swing.JTextField();
        englishTxtField = new javax.swing.JTextField();
        filipinoTxtField = new javax.swing.JTextField();
        scienceTxtField = new javax.swing.JTextField();
        gwaLabel = new javax.swing.JLabel();
        gwaTxtField = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        nextBtn3 = new javax.swing.JButton();
        termsandConditions = new javax.swing.JButton();
        returnbtn3 = new javax.swing.JButton();
        coursePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campusLabel1 = new javax.swing.JLabel();
        programLabel1 = new javax.swing.JLabel();
        campusOption1 = new javax.swing.JComboBox<>();
        programOption1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        campusLabel2 = new javax.swing.JLabel();
        programLabel3 = new javax.swing.JLabel();
        campusOption2 = new javax.swing.JComboBox<>();
        programOption2 = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        returnbtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 450));
        setSize(new java.awt.Dimension(950, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 22, 29), 2));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 22, 29));
        jLabel1.setText("UNIVERSITY ADMISSION");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BPSU (1).png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 80));

        jPanel2.setBackground(new java.awt.Color(85, 22, 29));

        personalInfoBtn.setText("Personal Information");
        personalInfoBtn.setBorder(null);
        personalInfoBtn.setPreferredSize(new java.awt.Dimension(45, 15));
        personalInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfoBtnActionPerformed(evt);
            }
        });

        educBackgroundBtn.setText("Educational Background");
        educBackgroundBtn.setBorder(null);
        educBackgroundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educBackgroundBtnActionPerformed(evt);
            }
        });

        gradesBtn.setText("Grades");
        gradesBtn.setBorder(null);
        gradesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradesBtnActionPerformed(evt);
            }
        });

        courseBtn.setText("Course");
        courseBtn.setBorder(null);
        courseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personalInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(educBackgroundBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(personalInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(educBackgroundBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(gradesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(courseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 75, 190, 340));

        personalInfoPanel.setBackground(new java.awt.Color(204, 204, 204));

        fullnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullnameLabel.setForeground(java.awt.Color.black);
        fullnameLabel.setText("STUDENT'S INFORMATION");

        lastNameTxtField.setBackground(new java.awt.Color(153, 153, 153));
        lastNameTxtField.setForeground(new java.awt.Color(0, 0, 0));
        lastNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("LAST NAME:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Date of Birth:");

        birthday.setBackground(new java.awt.Color(153, 153, 153));
        birthday.setDateFormatString("dd-MM-yyyy\n");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Sex:");

        emailAddLabel.setBackground(new java.awt.Color(204, 204, 204));
        emailAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailAddLabel.setForeground(new java.awt.Color(30, 30, 30));
        emailAddLabel.setText("Email Address:");

        addressLabel1.setBackground(new java.awt.Color(204, 204, 204));
        addressLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel1.setForeground(new java.awt.Color(30, 30, 30));
        addressLabel1.setText("Address:");

        studCpNumLabel.setBackground(new java.awt.Color(204, 204, 204));
        studCpNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studCpNumLabel.setForeground(new java.awt.Color(30, 30, 30));
        studCpNumLabel.setText("Phone Number:");

        addressTxtField.setBackground(new java.awt.Color(153, 153, 153));
        addressTxtField.setForeground(new java.awt.Color(30, 30, 30));
        addressTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFieldActionPerformed(evt);
            }
        });

        emailAddTxtField.setBackground(new java.awt.Color(153, 153, 153));
        emailAddTxtField.setForeground(new java.awt.Color(30, 30, 30));

        studCpnumTxtField.setBackground(new java.awt.Color(153, 153, 153));
        studCpnumTxtField.setForeground(new java.awt.Color(30, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Given Name:");

        givenNameTxtField.setBackground(new java.awt.Color(153, 153, 153));
        givenNameTxtField.setForeground(new java.awt.Color(0, 0, 0));
        givenNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                givenNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 30, 30));
        jLabel12.setText("Middle Name:");

        middleNameTxtField.setBackground(new java.awt.Color(153, 153, 153));
        middleNameTxtField.setForeground(new java.awt.Color(0, 0, 0));
        middleNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTxtFieldActionPerformed(evt);
            }
        });

        sexComboBox.setBackground(new java.awt.Color(153, 153, 153));
        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        sexComboBox.setBorder(null);

        nextBtn1.setBackground(new java.awt.Color(204, 204, 204));
        nextBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-forward-arrow-50.png"))); // NOI18N
        nextBtn1.setBorder(null);
        nextBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn1ActionPerformed(evt);
            }
        });

        returnbtn1.setBackground(new java.awt.Color(204, 204, 204));
        returnbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-arrow-24.png"))); // NOI18N
        returnbtn1.setBorder(null);
        returnbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personalInfoPanelLayout = new javax.swing.GroupLayout(personalInfoPanel);
        personalInfoPanel.setLayout(personalInfoPanelLayout);
        personalInfoPanelLayout.setHorizontalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addComponent(returnbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInfoPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3))
                            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(addressLabel1)
                                    .addComponent(emailAddLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                                        .addComponent(givenNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                                        .addComponent(middleNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studCpNumLabel))
                                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailAddTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalInfoPanelLayout.createSequentialGroup()
                        .addComponent(fullnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(birthday, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(sexComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(studCpnumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        personalInfoPanelLayout.setVerticalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(returnbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalInfoPanelLayout.createSequentialGroup()
                        .addComponent(fullnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personalInfoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(givenNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studCpNumLabel)
                        .addComponent(studCpnumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(middleNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel1)
                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("tab1", personalInfoPanel);

        educBGPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 22, 29));
        jLabel5.setText("Previous school attended:");

        returnbtn2.setBackground(new java.awt.Color(204, 204, 204));
        returnbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-arrow-24.png"))); // NOI18N
        returnbtn2.setBorder(null);
        returnbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtn2ActionPerformed(evt);
            }
        });

        nextBtn2.setBackground(new java.awt.Color(204, 204, 204));
        nextBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-forward-arrow-50.png"))); // NOI18N
        nextBtn2.setBorder(null);
        nextBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn2ActionPerformed(evt);
            }
        });

        schoolComboBox.setBackground(new java.awt.Color(102, 102, 102));
        schoolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Holy Rosary Parochial Insitute of Orani Inc.", "Our Lady of the Pillar Parochial School Inc.", "Saint Catherine of Siena Academy of Samal Inc.", "BLC Integrated School", "Bataan National High School", "Samal National High School", "Orani National High School", "Bataan Christian College Inc.", "Balanga City National Science High School", "None of the Given School [provide name]" }));
        schoolComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolComboBoxActionPerformed(evt);
            }
        });

        addSchoolTxtField.setBackground(new java.awt.Color(153, 153, 153));
        addSchoolTxtField.setForeground(new java.awt.Color(30, 30, 30));
        addSchoolTxtField.setText("Enter previous school");
        addSchoolTxtField.setBorder(null);
        addSchoolTxtField.setVisible(false);
        addSchoolTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchoolTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout educBGPanelLayout = new javax.swing.GroupLayout(educBGPanel);
        educBGPanel.setLayout(educBGPanelLayout);
        educBGPanelLayout.setHorizontalGroup(
            educBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educBGPanelLayout.createSequentialGroup()
                .addComponent(returnbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educBGPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(educBGPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addSchoolTxtField)
                    .addComponent(schoolComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        educBGPanelLayout.setVerticalGroup(
            educBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educBGPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(returnbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(educBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSchoolTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(nextBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("tab3", educBGPanel);

        gradespanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Enter grades from latest semester:");

        englishLabel.setBackground(new java.awt.Color(204, 204, 204));
        englishLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        englishLabel.setForeground(new java.awt.Color(30, 30, 30));
        englishLabel.setText("English:");

        mathLabel.setBackground(new java.awt.Color(204, 204, 204));
        mathLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mathLabel.setForeground(new java.awt.Color(30, 30, 30));
        mathLabel.setText("Mathematics:");

        scienceLabel.setBackground(new java.awt.Color(204, 204, 204));
        scienceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scienceLabel.setForeground(new java.awt.Color(30, 30, 30));
        scienceLabel.setText("Science:");

        filipinoLabel.setBackground(new java.awt.Color(204, 204, 204));
        filipinoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filipinoLabel.setForeground(new java.awt.Color(30, 30, 30));
        filipinoLabel.setText("Filipino:");

        mathTxtField.setBackground(new java.awt.Color(153, 153, 153));
        mathTxtField.setForeground(new java.awt.Color(30, 30, 30));

        englishTxtField.setBackground(new java.awt.Color(153, 153, 153));
        englishTxtField.setForeground(new java.awt.Color(30, 30, 30));

        filipinoTxtField.setBackground(new java.awt.Color(153, 153, 153));
        filipinoTxtField.setForeground(new java.awt.Color(30, 30, 30));

        scienceTxtField.setBackground(new java.awt.Color(153, 153, 153));
        scienceTxtField.setForeground(new java.awt.Color(30, 30, 30));

        gwaLabel.setBackground(new java.awt.Color(204, 204, 204));
        gwaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gwaLabel.setForeground(new java.awt.Color(30, 30, 30));
        gwaLabel.setText("GWA:");

        gwaTxtField.setBackground(new java.awt.Color(153, 153, 153));
        gwaTxtField.setForeground(new java.awt.Color(30, 30, 30));

        nextBtn3.setBackground(new java.awt.Color(204, 204, 204));
        nextBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-forward-arrow-50.png"))); // NOI18N
        nextBtn3.setBorder(null);
        nextBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn3ActionPerformed(evt);
            }
        });

        termsandConditions.setBackground(new java.awt.Color(204, 204, 204));
        termsandConditions.setForeground(new java.awt.Color(30, 30, 30));
        termsandConditions.setText("Terms and Conditions");
        termsandConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsandConditionsActionPerformed(evt);
            }
        });

        returnbtn3.setBackground(new java.awt.Color(204, 204, 204));
        returnbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-arrow-24.png"))); // NOI18N
        returnbtn3.setBorder(null);
        returnbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradespanelLayout = new javax.swing.GroupLayout(gradespanel);
        gradespanel.setLayout(gradespanelLayout);
        gradespanelLayout.setHorizontalGroup(
            gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradespanelLayout.createSequentialGroup()
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradespanelLayout.createSequentialGroup()
                        .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradespanelLayout.createSequentialGroup()
                                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gradespanelLayout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(gwaLabel)
                                            .addComponent(filipinoLabel)
                                            .addComponent(scienceLabel)
                                            .addComponent(mathLabel)
                                            .addComponent(englishLabel)))
                                    .addGroup(gradespanelLayout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(termsandConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(englishTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filipinoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scienceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gwaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1)))
                            .addGroup(gradespanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(returnbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gradespanelLayout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(jLabel6)))
                        .addGap(0, 276, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradespanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nextBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        gradespanelLayout.setVerticalGroup(
            gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradespanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(returnbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mathLabel)
                    .addComponent(mathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(englishLabel)
                    .addComponent(englishTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filipinoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filipinoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scienceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scienceLabel))
                .addGap(10, 10, 10)
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gwaLabel)
                    .addComponent(gwaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(gradespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(termsandConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(nextBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("tab2", gradespanel);

        coursePanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(85, 22, 29));
        jLabel8.setText("Choose Campus and Program");

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("First Choice:");

        campusLabel1.setBackground(new java.awt.Color(204, 204, 204));
        campusLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campusLabel1.setForeground(new java.awt.Color(0, 0, 0));
        campusLabel1.setText("Campus:");

        programLabel1.setBackground(new java.awt.Color(204, 204, 204));
        programLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        programLabel1.setForeground(new java.awt.Color(0, 0, 0));
        programLabel1.setText("Program:");

        campusOption1.setBackground(new java.awt.Color(153, 153, 153));
        campusOption1.setForeground(new java.awt.Color(30, 30, 30));
        campusOption1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abucay Campus", "Bagac Campus", "Balanga Campus", "Dinalupihan Campus", "Main Campus", "Orani Campus" }));
        campusOption1.setSelectedIndex(-1);
        campusOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campusOption1ActionPerformed(evt);
            }
        });

        programOption1.setBackground(new java.awt.Color(153, 153, 153));
        programOption1.setForeground(new java.awt.Color(30, 30, 30));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Second Choice:");

        campusLabel2.setBackground(new java.awt.Color(204, 204, 204));
        campusLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campusLabel2.setForeground(new java.awt.Color(0, 0, 0));
        campusLabel2.setText("Campus:");

        programLabel3.setBackground(new java.awt.Color(204, 204, 204));
        programLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        programLabel3.setForeground(new java.awt.Color(0, 0, 0));
        programLabel3.setText("Program:");

        campusOption2.setBackground(new java.awt.Color(153, 153, 153));
        campusOption2.setForeground(new java.awt.Color(30, 30, 30));
        campusOption2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abucay Campus", "Bagac Campus", "Balanga Campus", "Dinalupihan Campus", "Main Campus", "Orani Campus" }));
        campusOption2.setSelectedIndex(-1);
        campusOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campusOption2ActionPerformed(evt);
            }
        });

        programOption2.setBackground(new java.awt.Color(153, 153, 153));
        programOption2.setForeground(new java.awt.Color(30, 30, 30));

        saveBtn.setBackground(new java.awt.Color(85, 22, 29));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(204, 204, 204));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        returnbtn4.setBackground(new java.awt.Color(204, 204, 204));
        returnbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-arrow-24.png"))); // NOI18N
        returnbtn4.setBorder(null);
        returnbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(programLabel1)
                    .addComponent(campusLabel1)
                    .addComponent(campusLabel2)
                    .addComponent(programLabel3))
                .addGap(25, 25, 25)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(programOption1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campusOption1, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                    .addComponent(campusOption2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programOption2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coursePanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)))
                            .addGroup(coursePanelLayout.createSequentialGroup()
                                .addComponent(returnbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(jLabel8)))
                        .addGap(0, 293, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(returnbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campusLabel1)
                    .addComponent(campusOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programLabel1)
                    .addComponent(programOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(15, 15, 15)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campusLabel2)
                    .addComponent(campusOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programLabel3)
                    .addComponent(programOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("tab4", coursePanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, -35, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void personalInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfoBtnActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_personalInfoBtnActionPerformed

    private void educBackgroundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educBackgroundBtnActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_educBackgroundBtnActionPerformed

    private void lastNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtFieldActionPerformed

    private void gradesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradesBtnActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_gradesBtnActionPerformed

    private void courseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBtnActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_courseBtnActionPerformed

    private void returnbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtn1ActionPerformed
       this.dispose();
       new homePage().setVisible(true);
    }//GEN-LAST:event_returnbtn1ActionPerformed

    private void campusOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campusOption1ActionPerformed
        String selectedCampus = (String) campusOption1.getSelectedItem();
        updateProgramOptions(selectedCampus, programOption1);
    }//GEN-LAST:event_campusOption1ActionPerformed

    private void campusOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campusOption2ActionPerformed
        String selectedCampus = (String) campusOption2.getSelectedItem();
        updateProgramOptions(selectedCampus, programOption2);
    }//GEN-LAST:event_campusOption2ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String fullname = lastNameTxtField.getText() + "," + givenNameTxtField.getText() + middleNameTxtField.getText();
        String sex = (String) sexComboBox.getSelectedItem();
        String emailadd = emailAddTxtField.getText();
        String campus1 = (String) campusOption1.getSelectedItem();
        String program1 = (String) programOption1.getSelectedItem();
        String campus2 = (String) campusOption2.getSelectedItem();
        String program2 = (String) programOption2.getSelectedItem();
        String gwa = gwaTxtField.getText();
        
       studentData student = new studentData (fullname,sex, emailadd, campus1, program1, campus2, program2, gwa);
       userData.addStudent(student);
        
         JOptionPane.showMessageDialog(null, "Application sent! Please wait for further announcement!");
         this.dispose();
         new startingPage().setVisible(true);
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void givenNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_givenNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_givenNameTxtFieldActionPerformed

    private void middleNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTxtFieldActionPerformed

    private void addressTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtFieldActionPerformed

    private void nextBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn1ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_nextBtn1ActionPerformed

    private void nextBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn3ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_nextBtn3ActionPerformed

    private void termsandConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsandConditionsActionPerformed
        new termsandConditions().setVisible(true);
    }//GEN-LAST:event_termsandConditionsActionPerformed

    private void returnbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtn3ActionPerformed
       jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_returnbtn3ActionPerformed

    private void returnbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtn2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_returnbtn2ActionPerformed

    private void nextBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn2ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_nextBtn2ActionPerformed

    private void returnbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtn4ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_returnbtn4ActionPerformed

    private void schoolComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolComboBoxActionPerformed
        String selectedSchool = (String)schoolComboBox.getSelectedItem();
        addSchool(selectedSchool);
    }//GEN-LAST:event_schoolComboBoxActionPerformed

    private void addSchoolTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchoolTxtFieldActionPerformed

    }//GEN-LAST:event_addSchoolTxtFieldActionPerformed
    
      private void addSchool (String selectedSchool){
          if("None of the Given School [provide name]".equals(selectedSchool)){
              addSchoolTxtField.setVisible(true);
          }else{
              addSchoolTxtField.setVisible(false);
          }
      }
      
      private void updateProgramOptions(String selectedCampus, JComboBox<String> programComboBox) {
        programComboBox.removeAllItems(); // Clear existing items
        
        // Populate program options based on selected campus
        if ("Abucay Campus".equals(selectedCampus)) {
            programComboBox.addItem("");
            programComboBox.addItem("Program A2");
            programComboBox.addItem("Program A3");
        } else if ("Bagac Campus".equals(selectedCampus)) {
            programComboBox.addItem("Program B1");
            programComboBox.addItem("Program B2");
        }else if ("Balanga Campus".equals(selectedCampus)){
            programComboBox.addItem("Program C1");
            programComboBox.addItem("Porgram C2");
        }else if("Dinalupihan Campus".equals(selectedCampus)){
            programComboBox.addItem(selectedCampus);
        }else if("Main Campus".equals(selectedCampus)){
            programComboBox.addItem(selectedCampus);
        }else if("Orani Campus".equals(selectedCampus)){
            programComboBox.addItem(selectedCampus);
        }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(collegeAdmissionSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(collegeAdmissionSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(collegeAdmissionSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(collegeAdmissionSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userData userData = new userData();
                new collegeAdmissionSystem(userData).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addSchoolTxtField;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JTextField addressTxtField;
    private com.toedter.calendar.JDateChooser birthday;
    private javax.swing.JLabel campusLabel1;
    private javax.swing.JLabel campusLabel2;
    private javax.swing.JComboBox<String> campusOption1;
    private javax.swing.JComboBox<String> campusOption2;
    private javax.swing.JButton courseBtn;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JPanel educBGPanel;
    private javax.swing.JButton educBackgroundBtn;
    private javax.swing.JLabel emailAddLabel;
    private javax.swing.JTextField emailAddTxtField;
    private javax.swing.JLabel englishLabel;
    private javax.swing.JTextField englishTxtField;
    private javax.swing.JLabel filipinoLabel;
    private javax.swing.JTextField filipinoTxtField;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JTextField givenNameTxtField;
    private javax.swing.JButton gradesBtn;
    private javax.swing.JPanel gradespanel;
    private javax.swing.JLabel gwaLabel;
    private javax.swing.JTextField gwaTxtField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JLabel mathLabel;
    private javax.swing.JTextField mathTxtField;
    private javax.swing.JTextField middleNameTxtField;
    private javax.swing.JButton nextBtn1;
    private javax.swing.JButton nextBtn2;
    private javax.swing.JButton nextBtn3;
    private javax.swing.JButton personalInfoBtn;
    private javax.swing.JPanel personalInfoPanel;
    private javax.swing.JLabel programLabel1;
    private javax.swing.JLabel programLabel3;
    private javax.swing.JComboBox<String> programOption1;
    private javax.swing.JComboBox<String> programOption2;
    private javax.swing.JButton returnbtn1;
    private javax.swing.JButton returnbtn2;
    private javax.swing.JButton returnbtn3;
    private javax.swing.JButton returnbtn4;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> schoolComboBox;
    private javax.swing.JLabel scienceLabel;
    private javax.swing.JTextField scienceTxtField;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JLabel studCpNumLabel;
    private javax.swing.JTextField studCpnumTxtField;
    private javax.swing.JButton termsandConditions;
    // End of variables declaration//GEN-END:variables
}
