/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdmissionForm;

import javax.swing.JOptionPane;

/**
 *
 * @author HANNAH
 */
public class password extends javax.swing.JFrame {
    private user loggedInUser;
    private static String newPassword;
    /**
     * Creates new form Password
     */
    public password(user user) {
        this.loggedInUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        usernamePanel = new javax.swing.JPanel();
        changeUsernameLabel = new javax.swing.JLabel();
        newUsernameField = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        pwPanel = new javax.swing.JPanel();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        okpwBtn = new javax.swing.JButton();
        cancelpwBtn = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Change Username");

        usernamePanel.setBackground(new java.awt.Color(238, 240, 229));

        changeUsernameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        changeUsernameLabel.setForeground(new java.awt.Color(48, 77, 48));
        changeUsernameLabel.setText("Enter your new username:");

        newUsernameField.setBackground(new java.awt.Color(182, 196, 182));
        newUsernameField.setForeground(new java.awt.Color(48, 77, 48));

        okBtn.setBackground(new java.awt.Color(48, 77, 48));
        okBtn.setText("OK");
        okBtn.setToolTipText("");

        cancelBtn.setBackground(new java.awt.Color(48, 77, 48));
        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeUsernameLabel)
                    .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, usernamePanelLayout.createSequentialGroup()
                            .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(newUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(changeUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Password");

        pwPanel.setBackground(new java.awt.Color(204, 204, 204));
        pwPanel.setForeground(new java.awt.Color(238, 240, 229));

        newPasswordLabel.setBackground(new java.awt.Color(85, 22, 29));
        newPasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        newPasswordLabel.setForeground(new java.awt.Color(85, 22, 29));
        newPasswordLabel.setText("Enter your new password:");
        newPasswordLabel.setPreferredSize(new java.awt.Dimension(170, 16));

        newPasswordField.setBackground(new java.awt.Color(153, 153, 153));
        newPasswordField.setForeground(new java.awt.Color(48, 77, 48));

        okpwBtn.setBackground(new java.awt.Color(85, 22, 29));
        okpwBtn.setForeground(new java.awt.Color(255, 255, 255));
        okpwBtn.setText("OK");
        okpwBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okpwBtnActionPerformed(evt);
            }
        });

        cancelpwBtn.setBackground(new java.awt.Color(85, 22, 29));
        cancelpwBtn.setForeground(new java.awt.Color(238, 240, 229));
        cancelpwBtn.setText("Cancel");
        cancelpwBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelpwBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pwPanelLayout = new javax.swing.GroupLayout(pwPanel);
        pwPanel.setLayout(pwPanelLayout);
        pwPanelLayout.setHorizontalGroup(
            pwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pwPanelLayout.createSequentialGroup()
                            .addComponent(okpwBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelpwBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pwPanelLayout.setVerticalGroup(
            pwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okpwBtn)
                    .addComponent(cancelpwBtn))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pwPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pwPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    private void okpwBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okpwBtnActionPerformed
        newPassword = new String (newPasswordField.getPassword());
        
        if (newPassword.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a new password", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!isValidPassword(newPassword)){
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long and contain at least one digit, one uppercase letter, and one lowercase letter", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            userData.updatePassword(loggedInUser, newPassword);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Password changed successfully","Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_okpwBtnActionPerformed
    
    private boolean isValidPassword(String password){
        if (password.length() < 8){
            return false;
        }
        
        boolean hasDigit = false;
        boolean hasUpperCase = false;
        boolean hasLowerCase = false;
        
        for (char c : password.toCharArray()){
            if (Character.isDigit(c)){
                hasDigit = true;
            }else if(Character.isUpperCase(c)){
                hasUpperCase = true;
            }else if (Character.isLowerCase(c)){
                hasLowerCase = true;
            }
        }
        
        return hasDigit&& hasUpperCase && hasLowerCase;
    }
    
    public static String getNewPassword(){
        return newPassword;
    }
    
    private void cancelpwBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelpwBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelpwBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                user testUser = userData.getUsers()[0];
                new password(testUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelpwBtn;
    private javax.swing.JLabel changeUsernameLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JTextField newUsernameField;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton okpwBtn;
    private javax.swing.JPanel pwPanel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
