
package AdmissionForm;

import javax.swing.JOptionPane;

public class username extends javax.swing.JFrame {
    private user loggedInUser;
    private static String newUsername;

    public username(user user) {
        this.loggedInUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamePanel = new javax.swing.JPanel();
        changeUsernameLabel = new javax.swing.JLabel();
        newUsernameField = new javax.swing.JTextField();
        okunBtn = new javax.swing.JButton();
        cancelunBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Username");

        usernamePanel.setBackground(new java.awt.Color(204, 204, 204));

        changeUsernameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        changeUsernameLabel.setForeground(new java.awt.Color(85, 22, 29));
        changeUsernameLabel.setText("Enter your new username:");

        newUsernameField.setBackground(new java.awt.Color(153, 153, 153));
        newUsernameField.setForeground(new java.awt.Color(153, 153, 153));

        okunBtn.setBackground(new java.awt.Color(85, 22, 29));
        okunBtn.setForeground(new java.awt.Color(238, 240, 229));
        okunBtn.setText("OK");
        okunBtn.setToolTipText("");
        okunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okunBtnActionPerformed(evt);
            }
        });

        cancelunBtn.setBackground(new java.awt.Color(85, 22, 29));
        cancelunBtn.setForeground(new java.awt.Color(238, 240, 229));
        cancelunBtn.setText("Cancel");
        cancelunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelunBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeUsernameLabel)
                    .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, usernamePanelLayout.createSequentialGroup()
                            .addComponent(okunBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelunBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(newUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(changeUsernameLabel)
                .addGap(5, 5, 5)
                .addComponent(newUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okunBtn)
                    .addComponent(cancelunBtn))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelunBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelunBtnActionPerformed

    private void okunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okunBtnActionPerformed
          newUsername = newUsernameField.getText();
          
          if(newUsername.equals("")){
              JOptionPane.showMessageDialog(null, "Please enter a new username", "Error", JOptionPane.ERROR_MESSAGE);
          }else{
              userData.updateUsername(loggedInUser, newUsername);
              this.dispose();
              JOptionPane.showMessageDialog(null, "Username changed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
    }//GEN-LAST:event_okunBtnActionPerformed

    public static String getNewUsername(){
        return newUsername;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                user testUser = userData.getUsers()[0];
                new username(testUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelunBtn;
    private javax.swing.JLabel changeUsernameLabel;
    private javax.swing.JTextField newUsernameField;
    private javax.swing.JButton okunBtn;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
